### PR TITLE
Add Demo.Desktop and Demo.Android to solution

### PR DESCRIPTION
**Pull request by Neurofibromin**
as mentioned in: https://github.com/Splitwirez/avalonia-aero-theme/issues/4#issuecomment-2158383322
This allows IDEs to recognise all projects as part of the solution.

### CODE REVIEW

**Comment by Splitwirez** [comment]
@Neurofibromin So sorry for not getting back to you on this in a more timely manner - just as our discussion over in https://github.com/Splitwirez/avalonia-aero-theme/issues/4 was picking up, some stuff...uh...came up. I haven't forgotten though!

(mind you, if I don't get back to you properly in another 2 weeks' time, it might've *actually* slipped my mind, so please don't hesitate to @mention me at that point)

**Comment by Neurofibromin** [comment]
@Splitwirez

**Comment by Splitwirez** [comment]
@Neurofibromin So sorry for the delay...would've happened way sooner, but I somehow mistakenly thought you were PR-ing to `main`...

## Problem

Your change to `build/dotnet-version.props` interferes with building via e.g. `dotnet run` outside of Visual Studio.

Can you verify whether or not changing line 5 in that file to
```xml
<PropertyGroup Condition=" ('$(VisualStudioMajorVersion)' != '') AND ('$(VisualStudioMajorVersion)' >= '17') ">
```
still allows building with .NET 8 on your end? (and I guess make that change, if it does)

**Comment by Neurofibromin** [comment]
I changed the line and it works. Added the commit.

**Comment by Splitwirez** [comment]
@Neurofibromin Merged :+1:

**Pull request merged**
